# Generated by Django 3.1 on 2020-08-19 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('job_settings', models.JSONField(null=True, verbose_name='Job Settings')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Id')),
                ('background_task_id', models.CharField(max_length=1024, null=True, verbose_name='Background Task Id')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progress')),
                ('status', model_utils.fields.StatusField(choices=[('not_started', 'not_started'), ('queued', 'queued'), ('started', 'started'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('error', 'error')], default='not_started', max_length=100, no_check_for_status=True)),
                ('input_url', models.CharField(max_length=1024, verbose_name='Input URL')),
                ('job_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presets.jobtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Output Name')),
                ('video_encoder', models.CharField(default='h264', max_length=100, verbose_name='Video Encoder')),
                ('video_bitrate', models.PositiveIntegerField(verbose_name='Video Bitrate')),
                ('video_preset', models.CharField(default='faster', max_length=100, verbose_name='Video Preset')),
                ('audio_encoder', models.CharField(default='aac', max_length=100, verbose_name='Audio Encoder')),
                ('audio_bitrate', models.PositiveIntegerField(default=128000, verbose_name='Audio Bitrate')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Video Width')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Video Height')),
                ('status', model_utils.fields.StatusField(choices=[('not_started', 'not_started'), ('queued', 'queued'), ('started', 'started'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('error', 'error')], default='not_started', max_length=100, no_check_for_status=True)),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progress')),
                ('background_task_id', models.CharField(max_length=1024, null=True, verbose_name='Background Task Id')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
