# Generated by Django 3.1 on 2020-08-14 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputGroup',
            fields=[
                ('outputgrouppreset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presets.outputgrouppreset')),
            ],
            options={
                'abstract': False,
            },
            bases=('presets.outputgrouppreset',),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Output Name')),
                ('video_encoder', models.CharField(default='h264', max_length=100, verbose_name='Video Encoder')),
                ('video_bitrate', models.PositiveIntegerField(verbose_name='Video Bitrate')),
                ('video_preset', models.CharField(default='faster', max_length=100, verbose_name='Video Preset')),
                ('audio_encoder', models.CharField(default='aac', max_length=100, verbose_name='Audio Encoder')),
                ('audio_bitrate', models.PositiveIntegerField(default=128000, verbose_name='Audio Bitrate')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Video Width')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Video Height')),
                ('preset_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.outputgroup')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('job_settings', models.JSONField(null=True, verbose_name='Job Settings')),
                ('job_id', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Job Id')),
                ('celery_task_id', models.CharField(max_length=1024, null=True, verbose_name='Celery Task Id')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progress')),
                ('status', model_utils.fields.StatusField(choices=[('not_started', 'not_started'), ('queued', 'queued'), ('started', 'started'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('error', 'error')], default='not_started', max_length=100, no_check_for_status=True)),
                ('start', models.DateField(verbose_name='Start Time')),
                ('end', models.DateField(verbose_name='End Time')),
                ('input_url', models.CharField(max_length=1024, verbose_name='Input URL')),
                ('job_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presets.jobtemplate')),
                ('output_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.outputgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
