# Generated by Django 3.1 on 2020-09-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="output", name="end", field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AddField(
            model_name="output", name="start", field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
    ]
