# Generated by Django 3.1 on 2020-12-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_auto_20200923_0912"),
    ]

    operations = [
        migrations.RenameField(model_name="job", old_name="end", new_name="end_time",),
        migrations.RenameField(model_name="job", old_name="start", new_name="start_time",),
        migrations.RenameField(model_name="output", old_name="end", new_name="end_time",),
        migrations.RenameField(model_name="output", old_name="start", new_name="start_time",),
    ]
