# Generated by Django 3.1 on 2020-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_auto_20200923_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="priority",
            field=models.CharField(max_length=100, null=True, verbose_name="Priority"),
        ),
    ]
