# Generated by Django 3.1 on 2021-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201218_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drm_encryption',
            field=models.JSONField(null=True, verbose_name='DRM Encryption'),
        ),
        migrations.AddField(
            model_name='job',
            name='output_cdn_url',
            field=models.CharField(max_length=1024, null=True, verbose_name='Output CDN URL'),
        ),
    ]
