# Generated by Django 3.1 on 2020-08-14 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputGroupPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Output Group Name')),
                ('destination', models.CharField(max_length=1024, verbose_name='Destination')),
                ('segment_length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HLS Segments length')),
                ('directory_name', models.CharField(max_length=255, verbose_name='Directory Name')),
                ('encryption_method', models.CharField(max_length=100, null=True, verbose_name='Encryption Method')),
                ('encryption_key', models.CharField(max_length=1024, null=True, verbose_name='Encrytpion Key')),
                ('key_url', models.CharField(max_length=1024, null=True, verbose_name='Encryption Key URL')),
                ('output_settings', models.JSONField(null=True, verbose_name='Output Settings')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OutputPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Output Name')),
                ('video_encoder', models.CharField(default='h264', max_length=100, verbose_name='Video Encoder')),
                ('video_bitrate', models.PositiveIntegerField(verbose_name='Video Bitrate')),
                ('video_preset', models.CharField(default='faster', max_length=100, verbose_name='Video Preset')),
                ('audio_encoder', models.CharField(default='aac', max_length=100, verbose_name='Audio Encoder')),
                ('audio_bitrate', models.PositiveIntegerField(default=128000, verbose_name='Audio Bitrate')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Video Width')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Video Height')),
                ('preset_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presets.outputgrouppreset')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('settings', models.JSONField(null=True, verbose_name='Settings')),
                ('output_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presets.outputgrouppreset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
