# Generated by Django 3.1 on 2021-01-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0002_auto_20201218_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtemplate",
            name="playlist_type",
            field=models.CharField(
                blank=True,
                choices=[("vod", "VOD"), ("live", "Live")],
                help_text="Applicable only for adaptive streaming",
                max_length=100,
                null=True,
                verbose_name="VOD/Live",
            ),
        ),
        migrations.AlterField(
            model_name="jobtemplate",
            name="format",
            field=models.CharField(
                choices=[("hls", "HLS"), ("dash", "Dash"), ("hls_and_dash", "HLS And Dash")],
                default="h264",
                max_length=255,
                verbose_name="Output Format",
            ),
        ),
    ]
